export const FETCH_RANDOM_DATA = "FETCH_RANDOM_DATA";
export const FETCH_RANDOM_DATA_SUCCEEDED = "FETCH_RANDOM_DATA_SUCCEEDED";
export const FETCH_RANDOM_DATA_FILED = "FETCH_RANDOM_DATA_FILED";
export const SET_SELECTED_POINTS = "SET_SELECTED_POINTS";
